### ISSUE TITLE
Kubernetes Deployment of uEngine5

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/uEngine5-base#116]
# 우선, Netflix OSS 요소 설치하기 - 유레카

```
cd zerotodocker/eureka/1.3.1/
docker build -t gcr.io/perfect-victor-214004/eureka:v1 .   #gcr.io 가 들어가면 goole registry 에 등록됨
docker push gcr.io/perfect-victor-214004/eureka:v1

(nano ~/eureka.yml)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: gcr.io/perfect-victor-214004/eureka:v1     #전체 주소를 주야 함.


(kubectl delete deployments --l app=eureka)
kubectl apply -f ~/eureka.yml
kubectl get pods
kubectl describe pod eureka-deployment-7cddf689df-hxvzh    #pod가 일단 잘 디플로이 됐는지 확인

# 서비스(LoadBalancer) 등록 통한 외부노출


```

# Deployment 통한 무정지 재배포 
```
```
# 오토스케일링
```
```

# Availability 체크 통한  Self-Healing 관리
```
```

# ToDos
## 줄도 마찬가지로 작업
```
....
```

## 유엔진5 를 빌드하여 Kuber 에 배포할 준비. 
```
 TODOs
```

**Comment by jinyoung** [comment]
참고 - https://github.com/TheOpenCloudEngine/uEngine-cloud/wiki/Kubernetes-%EC%8B%A4%EC%8A%B5-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8

**Comment by jinyoung** [comment]
Todos
1. eureka 에 등록이 안되는 이유 확인 : 유레카 api 를 각 container 내에서 직접 호출해봐야 알 수 있을듯..
1. zuul 로 연결, zuul 을 LoadBalancer 를 통해 open
1. zuul 을 ingress 로 변경 - 변경에 의미가 있는가? 성능상 이점. 변경시 발생하는 문제, 유레카에 등록된 serviceId 를 첫번째 path 요소로 하여 자동 라우팅 되던 것이 ingress 에선 어떻게 되는가?

**Comment by jinyoung** [comment]
1. 문제의 해결:

```
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  labels:
    app: eureka
spec:
  ports:
  - port: 27017
    name: eureka    # 이 부분의 추가!
    protocol: TCP
  selector:
    app: eureka
```

DNS 의 name 이 되는 출처는 서비스의 이름이 아니라 저 ports 이하의 name 프로퍼티를 읽어간다는 사실.. ㅡㅡ;
